extends RefCounted
## Circular head at a centre and radius, with uncropped profile artwork.
## Cache this helper per view. Skin colour is independent of pixel art.
var _cache: Dictionary = {}

func decode(payload: String) -> Dictionary:
	if payload.length() > 800000: return {}
	if _cache.has(payload): return _cache[payload]
	var data: Variant = JSON.parse_string(payload) if not payload.is_empty() else null
	var width := 0
	var height := 0
	var pixels: Array = []
	var legacy := data is Array
	if legacy:
		pixels = data
		width = int(sqrt(pixels.size()))
		height = width
	elif data is Dictionary and data.get("v", 0) == 1:
		if typeof(data.get("w")) not in [TYPE_INT, TYPE_FLOAT] or typeof(data.get("h")) not in [TYPE_INT, TYPE_FLOAT]: return {}
		if data.w < 1 or data.w > 256 or data.h < 1 or data.h > 256: return {}
		if floor(data.w) != data.w or floor(data.h) != data.h: return {}
		width = int(data.get("w", 0))
		height = int(data.get("h", 0))
		if data.get("px") is Array: pixels = data.px
	if width <= 0 or height <= 0 or width > 256 or height > 256 or pixels.size() != width * height:
		return {}
	var image := Image.create(width, height, false, Image.FORMAT_RGBA8)
	image.fill(Color.TRANSPARENT)
	for i in pixels.size():
		var pixel: Variant = pixels[i]
		if pixel is String and pixel.length() == 7 and pixel.begins_with("#") and Color.html_is_valid(pixel):
			if not legacy or pixel.to_lower() != "#0f172a":
				image.set_pixel(i % width, i / width, Color(pixel))
	var decoded := {"texture": ImageTexture.create_from_image(image),
		"center": Vector2(24 - _offset(width, 14), 28 - _offset(height, 15)),
		"size": Vector2(width, height)}
	# Profile changes replace their cached texture; bound memory for long nights.
	if _cache.size() >= 32: _cache.clear()
	_cache[payload] = decoded
	return decoded

func _offset(side: int, small: float) -> float:
	if side == 32: return small
	if side == 16: return small + 8
	return (48.0 - side) / 2

func draw_face(canvas: CanvasItem, player: Dictionary, center: Vector2, radius: float, facing: float = 1.0) -> void:
	var skin := Color.from_string(str(player.get("skin_color", "#f5e9be")), Color("f5e9be"))
	canvas.draw_circle(center, radius, skin)
	var decoded := decode(str(player.get("avatar", "")))
	if not decoded.is_empty():
		var scale := radius / 12.0
		canvas.draw_set_transform(center, 0, Vector2(facing, 1))
		canvas.draw_texture_rect(decoded.texture, Rect2(-decoded.center * scale, decoded.size * scale), false)
		canvas.draw_set_transform(Vector2.ZERO)
	else:
		# Same three-quarter default as the shared LÖVE helper. Guest artwork is
		# generated by the host, not improvised by each renderer.
		var ink := Color(0.08, 0.09, 0.12)
		var scale := radius / 12.0
		for x in [0, 6]:
			canvas.draw_circle(center + Vector2(x * facing, -2) * scale, 1.2 * scale, ink)
		canvas.draw_line(center + Vector2(2 * facing, 5) * scale, center + Vector2(6 * facing, 5) * scale, ink, scale)
